[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "keystone-docs"
version = "0.0.0"
description = ""
authors = ["Pitt Center for Research Computing"]

[tool.poetry.dependencies]
python = ">=3.11"

