name: 🎯 Pull Request

on:
  pull_request:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/Build.yml
    secrets: inherit

  report-pr-status:
    name: Report PR Status
    runs-on: ubuntu-latest
    needs: [ build ]
    if: always()

    steps:
      - name: Check PR status
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
