name: Update Submodules

on:
  repository_dispatch:
    types: [ update-submodules ]

env:
  repo_name: ${{ github.event.client_payload.repo_name }}
  tag: ${{ github.event.client_payload.tag }}

jobs:
  update_modules:
    name: Update Submodules
    runs-on: ubuntu-latest
    steps:
      - name: Validate inputs
        run: |
          [[ "${{ env.repo_name }}" ]] || { echo "Input \"repo_name\" cannot be empty" ; exit 1; }
          [[ "${{ env.tag }}" ]] || { echo "Input \"tag\" cannot be empty" ; exit 1; }
    
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update submodule
        working-directory: docs/submodules/${{ env.repo-name }}
        run: |
          git branch
          git checkout ${{ env.tag }}

      - name: Update parent repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --allow-empty -m "Updates ${{ env.repo-name }} to ${{ env.tag }}"
          git push
