name: Update Submodules

on:
  repository_dispatch:
    types: [ update-submodules ]
    inputs:
      repo-name:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  update_modules:
    name: Update Submodules
    runs-on: ubuntu-latest
    steps:
      - name: Validate inputs
        run: |
          [[ "${{ inputs.repo-name }}" ]] || { echo "Input \"repo-name\" is required" ; exit 1; }
          [[ "${{ inputs.tag }}" ]] || { echo "Input \"tag\" is required" ; exit 1; }
    
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update submodule
        working-directory: docs/submodules/${{ inputs.repo-name }}
        run: git checkout ${{ inputs.tag }}

      - name: Update parent repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --allow-empty -m "Updates ${{ inputs.repo-name }} to ${{ inputs.tag }}"
          git push
